name: runner

on: [push, workflow_dispatch]

jobs:
  environment:
    # Inspecting the environment
    # https://docs.github.com/en/actions/learn-github-actions/environment-variables
    strategy:
      fail-fast: false
      matrix:
        number: [1, 2] # so to check if disk writes are persistent or not
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: fredrikaverpil/setup-pipx@v1.3

      - run: pipx install poetry

      - name: env
        run: env

      # commented out paths are not cross-platform or won't work

      - name: HOME
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd $HOME
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          ls -alh

      - name: "~"
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd ~
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          ls -alh

      - name: "~/.cache"
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd ~/.cache
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          ls -alh

      # - name: /home/runner/work
      #   if: ${{ runner.os != 'Windows' }}
      #   working-directory: /home/runner/work
      #   run: |
      #     pwd
      #     touch i_was_here_${{ matrix.number }}.txt
      #     ls -alh

      - name: RUNNER_TEMP
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd $RUNNER_TEMP
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          ls -alh

      - name: GITHUB_WORKSPACE
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          ls -alh

      - name: GITHUB_ACTION_PATH
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd $GITHUB_ACTION_PATH
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          ls -alh

      - name: RUNNER_TOOL_CACHE
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd $RUNNER_TOOL_CACHE
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          ls -alh

      # Windows

      # - name: HOME
      #   if: ${{ runner.os == 'Windows' }}
      #   run: |
      #     cd env:$HOME
      #     pwd
      #     touch i_was_here_${{ matrix.number }}.txt
      #     dir

      - name: "~"
        if: ${{ runner.os == 'Windows' }}
        run: |
          cd ~
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          dir

      - name: RUNNER_TEMP
        if: ${{ runner.os == 'Windows' }}
        run: |
          cd env:$RUNNER_TEMP
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          dir

      - name: GITHUB_WORKSPACE
        if: ${{ runner.os == 'Windows' }}
        run: |
          cd env:$GITHUB_WORKSPACE
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          dir

      - name: GITHUB_ACTION_PATH
        if: ${{ runner.os == 'Windows' }}
        run: |
          cd env:$GITHUB_ACTION_PATH
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          dir

      - name: RUNNER_TOOL_CACHE
        if: ${{ runner.os == 'Windows' }}
        run: |
          cd env:$RUNNER_TOOL_CACHE
          pwd
          touch i_was_here_${{ matrix.number }}.txt
          dir
