name: runner

on:
  pull_request:

jobs:
  environment:
    # Inspecting the environment
    # https://docs.github.com/en/actions/learn-github-actions/environment-variables
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: RUNNER_TEMP
        run: |
          cd ${{ env.RUNNER_TEMP }}
          pwd
          touch i_was_here.txt
          ls -alh

      - name: GITHUB_WORKSPACE
        run: |
          cd ${{ env.GITHUB_WORKSPACE }}
          pwd
          touch i_was_here.txt
          ls -alh

      - name: GITHUB_ACTION_PATH
        run: |
          cd ${{ env.GITHUB_ACTION_PATH }}
          pwd
          touch i_was_here.txt
          ls -alh

      - name: RUNNER_TOOL_CACHE
        run: |
          cd ${{ env.RUNNER_TOOL_CACHE }}
          pwd
          touch i_was_here.txt
          ls -alh
