name: runner

on: [push, workflow_dispatch]

jobs:
  environment:
    # Inspecting the environment
    # https://docs.github.com/en/actions/learn-github-actions/environment-variables
    strategy:
      fail-fast: false
      matrix:
        number: [1, 2] # so to check if disk writes are persistent or not
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: RUNNER_TEMP
        run: |
          cd ${{ env.RUNNER_TEMP }}
          pwd
          touch i_was_here_at_$(date).txt
          if [ "$RUNNER_OS" != "Windows" ]; then
            ls -alh
          else
            dir
          fi

      - name: GITHUB_WORKSPACE
        run: |
          cd ${{ env.GITHUB_WORKSPACE }}
          pwd
          touch i_was_here_at_$(date).txt
          if [ "$RUNNER_OS" != "Windows" ]; then
            ls -alh
          else
            dir
          fi

      - name: GITHUB_ACTION_PATH
        run: |
          cd ${{ env.GITHUB_ACTION_PATH }}
          pwd
          touch i_was_here_at_$(date).txt
          if [ "$RUNNER_OS" != "Windows" ]; then
            ls -alh
          else
            dir
          fi

      - name: RUNNER_TOOL_CACHE
        run: |
          cd ${{ env.RUNNER_TOOL_CACHE }}
          pwd
          touch i_was_here_at_$(date).txt
          if [ "$RUNNER_OS" != "Windows" ]; then
            ls -alh
          else
            dir
          fi
